import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import ModalProvider from '@/components/modal-provider'
import AuthProvider from '@/components/auth-provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { session, ...params }
}: {
  children: React.ReactNode
  params: { session: any }
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider />
        {children}
      </body>
    </html>
  )
}
